# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37d736837697dd8fda99856216aaa3f08d8ee2a09b407e500380894d464fe8aaf4974e669a2f9d4f3d0de4f0d2b16034960774d193a3c901a6735e2e5a073d4

test:
  secret_key_base: c943c5d4f7f7c413098d1e8d9291fa998cb7b1dfa54c80faa9be5c42a96f3021a04a3621c0b8681f85723a68d1c9dbf2f5781c6f89003183e19018d658d80442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
